<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEkkbdgp\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEkkbdgp/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerEkkbdgp.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerEkkbdgp\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerEkkbdgp\appProdProjectContainer([
    'container.build_hash' => 'Ekkbdgp',
    'container.build_id' => 'da5eb849',
    'container.build_time' => 1584809357,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEkkbdgp');
