<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'fullcalendar.service.calendar' shared service.

return $this->services['fullcalendar.service.calendar'] = new \Toiba\FullCalendarBundle\Service\Calendar(new \Toiba\FullCalendarBundle\Service\Serializer(), ${($_ = isset($this->services['debug.event_dispatcher']) ? $this->services['debug.event_dispatcher'] : $this->getDebug_EventDispatcherService()) && false ?: '_'});
