<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'EvenementBundle\EventListener\FullCalendarListener' shared autowired service.

return $this->services['EvenementBundle\\EventListener\\FullCalendarListener'] = new \EvenementBundle\EventListener\FullCalendarListener();
