<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYowh0yl\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYowh0yl/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerYowh0yl.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerYowh0yl\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerYowh0yl\appDevDebugProjectContainer([
    'container.build_hash' => 'Yowh0yl',
    'container.build_id' => '64d98bb6',
    'container.build_time' => 1585874137,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYowh0yl');
